'use client';
export const projects = [
  {
    title: 'Kamila ICMS School Management',
    description: 'Developed school management app and admin web for ICMS Boarding School using Flutter and Firebase. Includes attendance system for teachers and students, scoring, class schedule, daily and monthly reports and Parents monitoring. Authentication using Firebase Auth and database using Firestore.',
    youtubeLink: '',
    images: [
      '/images/projects/kamila_icms/kamila-icms-1.jpg',
      '/images/projects/kamila_icms/kamila-icms-2.jpg',
      '/images/projects/kamila_icms/kamila-icms-3.jpg',
      '/images/projects/kamila_icms/kamila-icms-4.jpg',
      '/images/projects/kamila_icms/kamila-icms-5.jpg',
    ],
    technologies: ['Flutter', 'Firebase'],
    liveDemo: '',
    github: '',
  },
  {
    title: 'ICMS Computer Based Test',
    description: 'Developed Computer Based Test website using Flutter and Firebase for ICMS Boarding School.',
    youtubeLink: '',
    images: [
      '/images/projects/icms_cbt/cbt-1.jpg',
      '/images/projects/icms_cbt/cbt-2.jpg',
      '/images/projects/icms_cbt/cbt-3.jpg',
      '/images/projects/icms_cbt/cbt-4.jpg',
      '/images/projects/icms_cbt/cbt-5.jpg',
      '/images/projects/icms_cbt/cbt-6.jpg',     
    ],
    technologies: ['Flutter', 'Firebase'],
    liveDemo: '',
    github: '',
  },
  {
    title: 'Foodies Recipe Sharing',
    description: 'Developed food recipe sharing app using Flutter and Firebase. Authentication using Firebase Auth and database using Firestore. Using Bloc state management and implementing clean architecture as needed.',
    youtubeLink: '',
    images: [
      '/images/projects/foodies/foodies-1.jpg',
      '/images/projects/foodies/foodies-2.jpg',
      '/images/projects/foodies/foodies-3.jpg',
      '/images/projects/foodies/foodies-4.jpg',
      '/images/projects/foodies/foodies-5.jpg',
      '/images/projects/foodies/foodies-6.jpg',
      '/images/projects/foodies/foodies-7.jpg',
      '/images/projects/foodies/foodies-8.jpg',
      '/images/projects/foodies/foodies-9.jpg',
      '/images/projects/foodies/foodies-10.jpg',
    ],
    technologies: ['Flutter', 'Firebase'],
    liveDemo: '',
    github: 'https://github.com/deswinar/Foodies-Flutter',
  },
  {
    title: 'Signature Recognition',
    description: 'Developed Desktop and Raspberry Pi application for name signature recognition using Python, PyTorch and LSTM Neural Network model.',
    youtubeLink: '',
    images: [
      '/images/projects/handsign_recognition/handsign-recognition-1.JPG',
      '/images/projects/handsign_recognition/handsign-recognition-2.JPG',
      '/images/projects/handsign_recognition/handsign-recognition-3.JPG',
      '/images/projects/handsign_recognition/handsign-recognition-4.JPG',
      '/images/projects/handsign_recognition/handsign-recognition-5.JPG',
    ],
    technologies: ['Python', 'PyTorch', 'LSTM model'],
    liveDemo: '',
    github: 'https://github.com/deswinar/Signature-Recognition',
  },
  {
    title: 'Snack Vending Machine',
    description: 'Developed the frontend of a snack vending machine using android OS hardware with native android. Includes polishing the TCP communication to the electrical hardware and payment method using digital e-wallet and cash.',
    youtubeLink: '3ZzksLliGzI',
    images: [
      '/images/projects/vending_machine/vending-machine-1.jpg',
      '/images/projects/vending_machine/vending-machine-2.jpg',
      '/images/projects/vending_machine/vending-machine-3.jpg',
    ],
    technologies: ['Android', 'Java', 'TCP'],
    liveDemo: '',
    github: '',
  },
  {
    title: 'Realtime Drowsiness Detection',
    description: 'Developed Android app using Kotlin for realtime drowsiness detection to help driver alerted if they are getting drowsy. Using YOLOV5 and TFLite.',
    youtubeLink: '',
    images: [
      '/images/projects/drowsy/drowsy-1.jpg',
      '/images/projects/drowsy/drowsy-2.jpg',
      '/images/projects/drowsy/drowsy-3.jpg',
      '/images/projects/drowsy/drowsy-4.jpg',
    ],
    technologies: ['Kotlin', 'YOLOV5', 'TFLite'],
    liveDemo: '',
    github: 'https://github.com/deswinar/Realtime-Drowsiness-Detection',
  },
  {
    title: 'Hartanzah Coffee Roasting (Frontend)',
    description: 'A mobile application to help Coffee Shop Owner and Barista manage and roaster coffee beans.',
    youtubeLink: '',
    images: [
      '/images/projects/coffee_roasting/coffee-roasting-1.jpg',
      '/images/projects/coffee_roasting/coffee-roasting-2.jpg',
      '/images/projects/coffee_roasting/coffee-roasting-3.jpg',
      '/images/projects/coffee_roasting/coffee-roasting-4.jpg',
    ],
    technologies: ['MIT App Inventor'],
    liveDemo: 'https://play.google.com/store/apps/details?id=appinventor.ai_rian_hartanzah.PRO_COFFEE_ROASTING_V02',
    github: '',
  },
  {
    title: 'Heart Disease Classification Website',
    description: 'A web application to classify Cardiomegaly and Coroner heart disease.',
    youtubeLink: '',
    images: [
      '/images/projects/heart_classification/heart-classification-1.jpg',
      '/images/projects/heart_classification/heart-classification-2.jpg',
      '/images/projects/heart_classification/heart-classification-3.jpg',
      '/images/projects/heart_classification/heart-classification-4.jpg',
      '/images/projects/heart_classification/heart-classification-5.jpg',
    ],
    technologies: ['Python', 'TensorFlow'],
    liveDemo: 'https://cardiomegalyclassification-s.streamlit.app/',
    github: 'https://github.com/deswinar/cardiomegaly_classification_web',
  },
];
